name: Lint
run-name: Linting ${{ github.repository }}

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install isort
        pip install black
        pip install mypy

    - name: Ruff Linter
      run: |
        ruff check . --diff

    - name: Isort Import Sorter
      run: |
        isort . --diff --check

    - name: Black Formatter
      run: |
        black . --diff --check

    - name: Mypy Type Checker
      run: |
        mypy . --install-types --non-interactive --check-untyped-defs --ignore-missing-imports
